apiVersion: apps/v1
kind: Deployment
metadata:
  name: yaml-validator
  labels:
    app: yaml-validator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yaml-validator
  template:
    metadata:
      labels:
        app: yaml-validator
    spec:
      containers:
      - name: yaml-validator
        image: <your-docker-image>
        ports:
        - containerPort: 5000
