apiVersion: v1
kind: Service
metadata:
  name: yaml-validator
  labels:
    app: yaml-validator
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: yaml-validator
